### PR TITLE
Add Matrix tf to Text and HTML backends

### PR DESCRIPTION
**Pull request by DhruvaSambrani**
#33, #37 , #35, #36

### CODE REVIEW

**Comment by ronisbr** [comment]
Perfect @DhruvaSambrani ! Thanks for that. The only think I will ask is to remove those commits related to the images. I have a local script to generate them that is based on the md5 sum. Thus, they will be replaced.

**Comment by DhruvaSambrani** [comment]
Done.

**Comment by ronisbr** [comment]
Hi @DhruvaSambrani ,

I loved this matrix output! Everything seems very good. I have only two comments:

1. I think that the `left_intersection` character of `ascii_matrix` is wrong.
2. Do we really need that `ascii_matrix`? The format (even when 1 is corrected) looks very, very bad:

Captura de Tela 2020-02-03 às 20 14 09

I vote to remove `ascii_matrix` and call `unicode_matrix` just `matrix`. I really thing that all those box characters are defined in extended ASCII (https://theasciicode.com.ar/extended-ascii-code/box-drawing-character-single-line-lower-left-corner-ascii-code-192.html).

**Comment by DhruvaSambrani** [comment]
Yeah, if they are in extended ascii, then it shouldn't be a problem.
Should I remove it?

**Comment by DhruvaSambrani** [comment]
Just a heads-up, Its not implemented for Latex.

**Comment by ronisbr** [comment]
> Should I remove it?

Yes, please, remove them, and rename the `unicode_matrix` to `matrix`.

> Just a heads-up, Its not implemented for Latex.

No problem! LaTeX still needs some work. We can just change the environment, should be easy. However, since I am planning for major changes, we can just let it untouched for now.

**Comment by DhruvaSambrani** [comment]
Done. Please do merge and release!

**Comment by ronisbr** [comment]
You did not change the `export`. It still have `simple, unicode_rounded, unicode_matrix, ascii_matrix`. After that, if the test passes, I will merge. However, I will only release a new version when I add the tests for this new code.

**Comment by DhruvaSambrani** [comment]
Yikes sorry. Changed. Thanks for your time!!

**Pull request merged**
