### PR TITLE
fix hline suffix bug

### PR DESCRIPTION
**Pull request by m-wells**
image
image

### CODE REVIEW

**Comment by m-wells** [comment]
I'm not sure what's up with `Invalidations`.
```
ERROR: package `PrettyTables [08abe8d2]` has same name or UUID as the active project
```

**Comment by m-wells** [comment]
@ronisbr Is there something I can do on my end to fix the failing test?

**Comment by ronisbr** [comment]
Hi @m-wells!

Thanks for the PR!

The problem with the invalidations is not related to this PR.

However, I think there is an error in your modification. I am pretty sure that if a cell is decorated (a highlighter for example) and it gets cropped by the display, the suffix will be decorated due to your PR, which will not be right. Can you test please?

**Comment by m-wells** [comment]
@ronisbr Looks good to me
image

**Comment by ronisbr** [comment]
Notice that the suffix … is being decorated with the last cell color. This behavior is not right. The suffix should not have a decoration.

**Comment by m-wells** [comment]
Ok. Here you go.
image

**Comment by m-wells** [comment]
Here you go.
image

**Comment by ronisbr** [comment]
Awesome! Thanks!

**Pull request merged**
