### PR TITLE
Adding rich output support for Markdown

### PR DESCRIPTION
**Pull request by NicholasWMRitchie**
I've added some simple code that permits rich output from Markdown cells in HTML and LaTeX.
I hope that you'll consider adding something like this to your fine package since it enables some really nice cell outputs - like URL links and images as well as rich text format.

### CODE REVIEW

**Comment by ronisbr** [comment]
This is awesome! Thanks :) I will try to take a look at it until tomorrow!

**Comment by NicholasWMRitchie** [comment]
I've been working with DataFrames and have been able to integrate Markdown input into their HTML, LaTeX, plain and csv text.  In the process, I've learned a bit and will make a couple of small changes to improve the output.

**Comment by NicholasWMRitchie** [comment]
It seems like the changes to DataFrames to support Markdown are stabilizing.
The one big difference is that Markdown output looks better when left justified as DataFrames does.  Right justification does weird things to some of the formatting elements.

**Comment by ronisbr** [comment]
This is good! I have some suggestions for Text but I think I can do it myself. It is working perfectly for LaTeX and HTML. Thank you very much for doing this :)

**Comment by ronisbr** [comment]
@NicholasWMRitchie I pushed some commits and now we have some conflicts. Can you please resolve them (it is very simple)? I do not know if I can do this myself.

**Comment by ronisbr** [comment]
I think I had a great idea! If I am correct, we can have multiple lines with markdown styling in Text mode. I will do this as soon as this gets merged.

**Comment by NicholasWMRitchie** [comment]
@ronisbr I've been on vacation but I'll get back to this ASAP.

**Comment by ronisbr** [comment]
> @ronisbr I've been on vacation but I'll get back to this ASAP.

OK! Thanks! The rebase is indeed very, very simple :) After that, I have a very good idea to have markdown support in cells with line breaks.

**Comment by NicholasWMRitchie** [comment]
I believe the equivalent changes in DataFrames are complete and now the conflicts here should be resolved.

**Comment by ronisbr** [comment]
Excellent! I will merge :) Thanks for the work!

**Pull request merged**
