### PR TITLE
Auto infer backend

### LINKED ISSUE #40: Make backend auto-inferred from the tf
Since tfs are of different types, backend can be inferred from the type.
```
⋮
_type_backend_dict = Dict{DataType, Symbol}(TextFormat=>:text, ... )

function pretty_table(..., tf=unicode, ...)
backend = _type_backend_dict[typeof(tf)]
⋮
```

### PR DESCRIPTION
**Pull request by DhruvaSambrani**
Fixed #40

### CODE REVIEW

**Comment by DhruvaSambrani** [comment]
Small issue,  I don't have a branch without the changes i made to implement the Matrix. You'll have to merge both. Sorry for that

**Comment by ronisbr** [comment]
I really liked this backend inference. Nice job!

I think you can do the following to create a new PR with only these changes. It will be easier for us in case we have a regression to revert.

```
git checkout -b new_branch
git reset --hard <SHA of a commit before your very first change>
git cherry-pick 3707e85
git cherry-pick 91327bb
git cherry-pick 01d0d55
```

Do some tests, and if everything is right, commit this `new_branch`  and open a new PR. Can you please do that? I would like to merge this inference before the matrix :)

**Comment by ronisbr** [comment]
By the way, with those commands, we remove that commit related to the images also.

**Comment by ronisbr** [comment]
Never mind, I could do exactly the same thing (preserving authoring).

**Pull request closed without merging**
