### PR TITLE
Booktabs formatter

### PR DESCRIPTION
**Pull request by gustaphe**
Add booktabs formatter and documentation.

### CODE REVIEW

**Comment by ronisbr** [comment]
Am I missing something, or this PR also contains the code merged in the last PR?

**Comment by ronisbr** [comment]
Never mind, I understand what's going on :D I will merge when tests are finished. Thanks!

**Comment by gustaphe** [comment]
Yeah, sorry. Bit of a nightmerge. Managed to pull in an unrelated commit. Must have reset a step too far.

**Comment by ronisbr** [comment]
I think Github identify it is the same commit and just let we merge the new ones.

**Pull request merged**
