### PR TITLE
Suggested patch release: allow Tables 1.0

### PR DESCRIPTION
**Pull request by tlienart**
(no changes required, tests pass afaict)

Note: this is blocking us upgrading MLJ to Tables 1.0 😄 also you may  want to use [CompatHelper.jl](https://github.com/bcbi/CompatHelper.jl) ?

### CODE REVIEW

**Comment by ronisbr** [comment]
Thanks! I will definitely take a look at CompatHelper.jl. I did not about this package until now :)

**Comment by ronisbr** [comment]
The new version should be available very soon.

**Comment by ronisbr** [comment]
@tlienart done! Can you test, please, if everything is right now so that you can upgrade the Tables.jl version in MLJ?

**Comment by tlienart** [comment]
all good thanks

**Pull request merged**
