### PR TITLE
Add decoration style

### PR DESCRIPTION
**Pull request by disberd**
Closes https://github.com/ronisbr/PrettyTables.jl/issues/134

### CODE REVIEW

**Comment by ronisbr** [comment]
Nice catch! Let's see if the tests pass.

**Comment by ronisbr** [comment]
ITMT, can you add some documentation for it?

**Comment by disberd** [comment]
I never added any documentation so do you have any references to look up on how to do this?

**Comment by ronisbr** [comment]
Oh ok! No problem! I will do that later.

**Pull request merged**
